In [5]:
import selenium
from selenium import webdriver
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

#open automated. chrome
driver=webdriver.Chrome(r'/Users/rinki/Downloads/chromedriver')

In [6]:
#open the website
url='https://www.naukri.com/'
driver.get(url)

#search job skill,designation

search_title=driver.find_element_by_xpath('/html/body/div/div[2]/div[3]/div/div/div[1]/div/div/div/input')
search_title

#search "Data Analyst"
search_title.send_keys("Data Scientist")

#Search location Delhi/NCR

search_location=driver.find_element_by_xpath('/html/body/div/div[2]/div[3]/div/div/div[3]/div/div/div/input')
search_location

search_location.send_keys("Delhi/NCR")


#search the selected options

search_button=driver.find_element_by_xpath('/html/body/div/div[2]/div[3]/div/div/div[6]')
search_button

search_button.click()

#scarpe Top 10 Job_title
job_title=driver.find_elements_by_xpath('//a[@class="title fw500 ellipsis"]')
job_title

Designation=[]
for i in job_title:
    Designation.append(i.text)
Designation

#Scrape location
job_location=driver.find_elements_by_xpath('//li[@class="fleft grey-text br2 placeHolderLi location"]')
job_location

Location=[]
for i in job_location:
    Location.append(i.text)
Location

#scrape company_name
org_detail=driver.find_elements_by_xpath('//a[@class="subTitle ellipsis fleft"]')
org_detail

organisation=[]
for i in org_detail:
   organisation.append(i.text)
organisation


#Make DataFrame of 10 Data Scientist
Data_Scientist=pd.DataFrame({})
Data_Scientist['Designation']=Designation[:10]
Data_Scientist['Location']=Location[:10]
Data_Scientist['organisation']=organisation[:10]
Data_Scientist

,Designation,Location,organisation
0,Forecasting Analyst/ Data Scientist (US Client),"Gurgaon/Gurugram, Bangalore/Bengaluru\n(WFH du...",Concentrix
1,"Excellent Opportunity For Freshers For AI/ML, ...","Noida, Kolkata, Hyderabad/Secunderabad, Pune, ...",NTT Data
2,Senior Data Scientist,"Noida, Pune, Bangalore/Bengaluru",Precisely
3,Virtusa Hiring DATA Scientist- PAN India,"Hyderabad/Secunderabad, Pune, Gurgaon/Gurugram...",Virtusa
4,Urgent Requirement - Data Scientist For a lead...,"Hyderabad/Secunderabad, Chennai, Bangalore/Ben...",BLJ TECH GEEKS
5,Senior Data Scientist,"Kochi/Cochin, Hyderabad/Secunderabad, Pune, Ch...",L A Consultancy
6,Associate Solution Architect (Data Scientist),"Hyderabad/Secunderabad, Pune, Chennai, Bangalo...",Apisero
7,Hiring Senior Data Scientist (6-8 yrs) | Remot...,Remote,Priority Vendor Technologies Pvt. Ltd.
8,Need Data Scientist,"Noida, Hyderabad/Secunderabad, Pune, Gurgaon/G...",AUREUSTECH SYSTEMS PRIVATE LIMITED
9,Data Scientist/ Analyst Specialist,"Noida, New Delhi, Gurgaon/Gurugram, Delhi / NC...",TransOrg Solutions Services (P) Ltd.